
// product test
DELETE  http://localhost:3000/api/v1/product/


// Brand test
###
DELETE  http://localhost:3000/api/v1/brand/

###

GET http://localhost:3000/api/v1/category?hi=1

###
GET  http://localhost:3000/test-api/get-cat/